service: aws-go-lambda

provider:
  name: aws
  runtime: go1.x

package:
  individually: true
  exclude:
    - ./**

functions:
  addTodo:
    handler: bin/handlers/addTodo
    package:
      include:
        - ./bin/handlers/addTodo
    events:
      - http:
          path: todos
          method: post
          cors: true
